# Setup
title: Andrew Lindner
tagline:
url: ''
paginate: 5
baseurl: ''
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: UA-170158194-1

# Specify the author for blog posts
author:
  name: Andrew Lindner
  url: ''
  email: andrew.lindner.blog@gmail.com

# Custom vars
version: 3.0.0
